### your site title here

title: Elle Brown
description: pronouns they/them | affiliations | Who says? Why not?

baseurl: "" #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: #

sass:
    sass_dir: /assets/css/_sass

highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
paginate_path: page:num/

# Social media links in footer
linkedin: "ellean"
github: "unrulybeep"

highlighter: rouge
markdown: kramdown

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
  resume:
    output: false

include: ['_pages', '_projects', '_resume']

programmingSkills:
  - skill1:
    name:
    percentage: 100%
  - skill2:
    name:
    percentage:
  - skill3:
    name: "JavaScript"
    percentage: 70%
  - skill4:
    name: "Java"
    percentage: 70%
  - skill5:
    name: "Google App Scripts/Engine"
    percentage: 75%
  - skill6:
    name:
    percentage:
designSkills:
  - skill1:
    name: "Photoshop"
    percentage: 80%
  - skill2:
    name: "InDesign"
    percentage: 40%
  - skill3:
    name:
    percentage: 100%
  - skill4:
    name:
    percentage: 90%
  - skill5:
    name:
    percentage: 75%
frontend:
  - skill1:
    name: "React.js"
    percentage: 80%
  - skill2:
    name: "Bootstrap"
    percentage: 90%
  - skill3:
    name: "HTML/CSS"
    percentage: 100%
  - skill4:
    name: "Sass"
    percentage: 90%
  - skill5:
    name: "Liquid"
    percentage: 85%
frameWorks:
  - skill1:
    name: Jekyll
  - skill2:
    percentage: 90%
  - skill3:
    name: Kirby
    percentage: 75%
  - skill4:
    name: Drupal
    percentage: 70%


exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-paginate
  - jekyll-email-protect
