### your site title here

title: Your Name
description: subtitle | affiliations | motto

baseurl: / #name of GitHub repository
url: "https://unrulybeep.github.io/" #custom url to be used instead of GitHub repository
email: #


highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
paginate_path: page:num/

# Social media links in footer
facebook: "#"
twitter: "#"
linkedin: "#"
github: "#"
researchgate: "#"
orcid: "#"

highlighter: rouge
markdown: kramdown

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: projects/:path/

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-paginate
  - jekyll-email-protect
