### your site title here

title: Your Name
description: pronouns they/them | affiliations | motto

baseurl: / #name of GitHub repository
url: "https://unrulybeep.github.io/" #custom url to be used instead of GitHub repository
email: #

sass:
    sass_dir: /assets/css/_sass

highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
paginate_path: page:num/

# Social media links in footer
linkedin: "ellean"
github: "unrulybeep"

highlighter: rouge
markdown: kramdown

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
  resume:
    output: true
    order:
      - program-coordinator.md
      - research-assistant.md
      - student-assistant.md
      - intern.md

include: ['_pages', '_projects', '_resume']

programmingSkills:
  - skill1:
    name:
    percentage: 100%
  - skill2:
    name: "Bootstrap"
    percentage: 90%
  - skill3:
    name: "JavaScript"
    percentage: 70%
  - skill4:
    name: "Java"
    percentage: 70%
  - skill5:
    name: "Google App Scripts (GAS)"
    percentage: 75%
  - skill6:
    name: "Liquid"
    percentage: 75%
designSkills:
  - skill1:
    name: "Photoshop"
    percentage: 80%
  - skill2:
    name: "InDesign"
    percentage: 40%
  - skill3:
    name: "HTML/CSS"
    percentage: 100%
  - skill4:
    name: "Sass"
    percentage: 90%
  - skill5:
    name:
    percentage: 75%
workshopsCerts:
  - entry1:
    type: "UW Workshop"
    title:
    instructor:
    date:
  - entry2:
    type: "UW Workshop"
    title: "How to make PDFs accessible"
    instructor: "Anna Marie Golden, MHCID - IT Accessibility Specialist"
    date: "June 2018"
  - entry3:
    type: "UW Workshop"
    title: "How to make web content accessible"
    instructor: "Anna Marie Golden, MHCID - IT Accessibility Specialist"
    date: "June 2018"
  - entry4:
    type: "workshop"
    title: UndocuAlly
    instructor: "Leaders without Borders"
    date: 2019
    url: "https://depts.washington.edu/ecc/lwb/"
  - entry5:
    type: "UW Workshop"
    title: Green Dot
    instructor: "LiveWell UW"
    date: 2017
    url: "https://www.washington.edu/news/2011/12/07/green-dot-now-a-cfd-choice-seeks-to-reduce-personal-power-based-violence"
  - entry6:
    type: LinkedIn
    title: "Google Apps Script for JavaScript Developers"
    instructor: Jesse Freeman
    date: 2021
    url: "https://www.linkedin.com/learning/google-apps-script-for-javascript-developers"
  - entry7:
    type: LinkedIn
    title: "Google Sites Essential Training"
    instructor: Jess Stration
    date: 2021
    url: "https://www.linkedin.com/learning/google-sites-essential-training-3"
  - entry8:
    type: LinkedIn
    title: "Microsoft Collaboration SharePoint, Teams, and Groups"
    instructor: Gini von Courter
    date: 2021
    url: "https://www.linkedin.com/learning/microsoft-collaboration-sharepoint-teams-and-groups"

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-paginate
  - jekyll-email-protect
